export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Main } from "./Main";
export { default as Expertise } from "./Expertise";
export { default as Certifications } from "./Certifications";
export { default as Timeline } from "./Timeline";
export { default as Education } from "./Education";
export { Languages } from "./Languages.tsx";
export { default as Hobbies } from "./Hobbies";
export { default as Project } from "./Project";
export { default as PersonalProjects } from "./PersonalProjects";
export { default as Courses } from "./Courses";
export { default as Contact } from "./Contact";
